[ ! -d /etc/confd ] && mkdir -p /etc/confd/{etcd,conf.d,templates}
cd /etc/confd
[ ! -e /usr/bin/confd ] && wget https://github.com/kelseyhightower/confd/releases/download/v0.12.0/confd-0.12.0-linux-amd64 && mv confd-0.12.0-linux-amd64 /usr/bin/confd
chmod 755 /usr/bin/confd

cat > etcd/ca.pem << EOF
-----BEGIN CERTIFICATE-----
MIIDwDCCAqigAwIBAgIUf+qXJOfLtrxlN8uBI1HEZOezf0owDQYJKoZIhvcNAQEL
BQAwZjELMAkGA1UEBhMCUEgxDzANBgNVBAgTBm1hbmlsYTELMAkGA1UEBxMCQ0Ex
EjAQBgNVBAoTCXNreWx1c3RlcjELMAkGA1UECxMCT00xGDAWBgNVBAMTD2V0Y2Qg
Y2x1c3RlciBDQTAeFw0xNzA4MTEwMjI4MDBaFw0yMjA4MTAwMjI4MDBaMGYxCzAJ
BgNVBAYTAlBIMQ8wDQYDVQQIEwZtYW5pbGExCzAJBgNVBAcTAkNBMRIwEAYDVQQK
Ewlza3lsdXN0ZXIxCzAJBgNVBAsTAk9NMRgwFgYDVQQDEw9ldGNkIGNsdXN0ZXIg
Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDw55FPFLwJUaMJCPer
mXLaTuzkjKuesNj8gtYc6qgiIP1QyDSRaxSy6RtNS8Xgsgt3NZ1pVvSFmcwT/yAl
b5WYG5wG3t//PUJ4G3WddrcVCS1IpEPr7NBm+L351ZMuZn3dY0wkyywMPUEvuJcb
p2p9a2ZrvmatjDb3qhosSIpWgNiLi53VI71FAMpZs1TVuiX4REg0I+QR86u/2J3g
2u/v1+sfTa3iAKh7t4lhR/qjuWnguduryKxF9fah/aNz6AHgJYUhCtuGKuH2S5YW
RQKfGC8awBYIU/pndlxe3ltYswFUtg05Lz9zrEx+fWeHiETmXfHfFQIGvUZ2FGfg
2rbBAgMBAAGjZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEC
MB0GA1UdDgQWBBTkemNLdlZHpN6Xt1Ps1KCkidfRfjAfBgNVHSMEGDAWgBTkemNL
dlZHpN6Xt1Ps1KCkidfRfjANBgkqhkiG9w0BAQsFAAOCAQEAZz1xghF8v4qZ/Tn9
n4fgu050vLIM5/5p4wg3Y7WlkEbM6lneA1KyBcsfKCN6OvOfp04s6HLichUSeSjI
Bnaa9yOVwd6vFCmmaPEgooY5PJcxye9iAwSn/jZcoG08cMKPnvJ93NCs/eJ0cjyn
x9l2HXkCxLH3GjqY0Hxw1wNmnsUqlzpfuLUkaB1mmBAXy14Efi3+ZUsEjJFTQJ1p
zpKnz5/gnVRJfGWfHOtSOOF6xLB5+UZs0I9E+733W3vlPSxDcqSxxkPtLis6qSFS
nsRKeXn4DMclyAvb5VW4I8zIEyNBxRm50tksTmmdQ/+BbqujQnUUN61/jy6sxuVw
i+Clfg==
-----END CERTIFICATE-----
EOF

cat > etcd/client.pem << EOF
-----BEGIN CERTIFICATE-----
MIIC6TCCAdGgAwIBAgIUS4ngBQ1hAp+6JJLOxbogOrcqcF4wDQYJKoZIhvcNAQEL
BQAwZjELMAkGA1UEBhMCUEgxDzANBgNVBAgTBm1hbmlsYTELMAkGA1UEBxMCQ0Ex
EjAQBgNVBAoTCXNreWx1c3RlcjELMAkGA1UECxMCT00xGDAWBgNVBAMTD2V0Y2Qg
Y2x1c3RlciBDQTAeFw0xNzA4MTEwMzIyMDBaFw0yMjA4MTAwMzIyMDBaMDwxCzAJ
BgNVBAYTAlBIMQ8wDQYDVQQIEwZNQU5JTEExCzAJBgNVBAcTAkNBMQ8wDQYDVQQD
EwZjbGllbnQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQL5e9683dZAIvhsNo3
ZPYerWGR/u4ccOuJiCnM1d6f9LtwvE68mEA1nCJJZGFmBm+Trh84h6PP10FO+IJH
ewNQo4GDMIGAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDAjAM
BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQXpYmSe8Iv1wsvutMcwqEg742tqjAfBgNV
HSMEGDAWgBTkemNLdlZHpN6Xt1Ps1KCkidfRfjALBgNVHREEBDACggAwDQYJKoZI
hvcNAQELBQADggEBAIyZYxydwhRImOGcxjqP6vSwuMiDym2axZQt0sVScTBydgBh
eOysLj8wiXFpzXhIlQTjUtUYefekqSFBFgYg97GLATLBIxC7OkjyEbFWyANgCBjm
R/cgd434EJFqQ3VwM13NpNVmE+PqlDmw0u6najDFC1ptWQucdCuh1eZ0t4SZzQa8
pJrG3LT0EeBKpr9GDPvHRal/qNE9RhMfX28xI+t0rxJ8liU8eKQybE2YqyYinGNB
dQMe9Whd4fLZX8wpJOg+lsCAYmM7cTo2e4Afg2vTdS7bYxjti8qNb5KmfVKVp4Fx
E+ARxak1YR9EMoXzQxJJ+NUQHLdw/0JlOEyQReg=
-----END CERTIFICATE-----
EOF

cat > etcd/client-key.pem << EOF
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEICvnXlChY6IaUcjeeDCjH+wjeuzX4RHd21xlszuYsR5EoAoGCCqGSM49
AwEHoUQDQgAEC+XvevN3WQCL4bDaN2T2Hq1hkf7uHHDriYgpzNXen/S7cLxOvJhA
NZwiSWRhZgZvk64fOIejz9dBTviCR3sDUA==
-----END EC PRIVATE KEY-----
EOF

chmod 600 etcd/*

cd /etc/confd/etcd
nohup confd -interval 10 -backend etcd -client-ca-keys ./ca.pem -client-cert ./client.pem -client-key ./client-key.pem -node https://69.172.86.20:2379 &